# Generated by Django 4.1.7 on 2023-02-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_createnotes_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('create_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_notes', to='notes.createnotes')),
                ('list_of_media', models.ManyToManyField(related_name='media_notes', to='notes.medianotes')),
            ],
        ),
    ]
