# Generated by Django 4.1.7 on 2023-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_medianotes_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medianotes',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medianotes',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
